Added new library app project
Vishal-raj-1/Awesome-JavaScript-Projects pull request #1056
Opened 2021-04-16 18:14 UTC by Muskan-creator

## Related Issue
  Added a new library app project in which  user can make a list of books with their authors, book pages and keep them as records. You just have to type the book information in the text fields and click on the add button to add the information on the record. This project includes a lot of javascript for making the functioning of the project. The user can add the number of book details and you can see the details stored in the list form. The user can delete the list of items if he/she wants to remove them.

Closes: #1050 

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
![image](https://user-images.githubusercontent.com/59757988/115066847-b8473e00-9f0d-11eb-8d10-1e78d56393a0.png)

2021-04-21 05:38 UTC, 991rajat commented on assets/css/styles.css
>    outline: none;
this file is not required I think. Don't push this one.

2021-04-21 05:41 UTC, 991rajat requested changes
Works great. Do you know CSS? If not tell me, will create a new issue for styling
Rightnow it looks pretty simple, add some css to make it look good.

And also reduce the size of the gif if possible. If not you can create a staic image and replace it with. This will be of smaller size.

2021-04-24 15:41 UTC, Muskan-creator commented
@991rajat I have added more styling to project and also resolve conflicts.
Please merge it and also add levels to it .

2021-04-25 07:14 UTC, 991rajat commented on script.js
>      projectName: 'JavaScript Interest Calculator',
Remove the counter and there is { missing for interest calculator.

2021-04-25 07:15 UTC, 991rajat requested changes
Looks Good, Just do the changes in script.js. It will be ready to merge.

2021-04-28 10:54 UTC, merged