Profile card
Vishal-raj-1/Awesome-JavaScript-Projects pull request #1081
Opened 2021-04-18 10:34 UTC by janvi01

## Related Issue
  - fixes issue #736 

Closes: #736 

### Describe the changes you've made
Added a Profile Card Generator.

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

Please review my code.

2021-04-21 09:14 UTC, 991rajat commented
@janvi01  Add the project to script.js.

2021-04-21 10:19 UTC, janvi01 commented
Is it okay now? @991rajat

2021-04-21 10:55 UTC, 991rajat commented on script.js
> +  {
Only Add you project. You have added other projects again too. Fix this please

2021-04-21 10:57 UTC, 991rajat requested changes
![image](https://user-images.githubusercontent.com/38184186/115542848-55afc280-a2be-11eb-9e49-b44b79fb33cb.png)
Make the buttons horizontally parallel

2021-04-21 11:21 UTC, janvi01 commented
is it okay now? @991rajat

2021-04-21 11:37 UTC, 991rajat commented
Could you please fix script.js too.
Add only your project.

2021-04-21 12:24 UTC, janvi01 commented
I have added in previous commit only, 
please check @991rajat

2021-04-23 12:59 UTC, 991rajat commented
@janvi01 Remove line 237-381
and add this insted.
 {
    projectName: "Profile Card Generator",
    projectImage: "assets/Images/Profilecard.png",
    projectUrl: "public/profilecard.html",
  },
  
  It will fix it.

2021-04-23 13:59 UTC, closed without merging

2021-04-23 14:08 UTC, janvi01 commented
I am making new PR, sorry for the inconvenience

2021-04-23 15:52 UTC, 991rajat commented
NO problem.