quiz
Vishal-raj-1/Awesome-JavaScript-Projects pull request #114
Opened 2021-02-17 12:58 UTC by ridhuridhu

## Related Issue
  - Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

2021-02-17 13:58 UTC, Vishal-raj-1 reviewed
Show me the UI, and remove extra unnecessary lines..

2021-02-18 05:14 UTC, ridhuridhu commented
![Screenshot (220)](https://user-images.githubusercontent.com/54496541/108308680-286b6900-71d6-11eb-99fb-218e30fa355b.png)
![Screenshot (221)](https://user-images.githubusercontent.com/54496541/108308686-2a352c80-71d6-11eb-83af-e39124d84799.png)
![Screenshot (222)](https://user-images.githubusercontent.com/54496541/108308689-2b665980-71d6-11eb-82cc-4a3ea3157d51.png)
![Screenshot (223)](https://user-images.githubusercontent.com/54496541/108308690-2bfef000-71d6-11eb-91ce-b5ac21c5affd.png)

2021-02-18 08:48 UTC, urvashi-code1255 requested changes
Hey @ridhuridhu your files are having so many unwanted space!! Remove all the spaces!! I have pointed some of them!!

But remove all of them! there should be only one line of space between every two lines!

2021-02-18 08:48 UTC, urvashi-code1255 commented on assets/css/quiz.css
> +
remove extra space

2021-02-18 08:48 UTC, urvashi-code1255 commented on assets/js/quiz.js
> +
remove extra space

2021-02-18 08:48 UTC, urvashi-code1255 commented on assets/js/quiz.js
> +
remove extra space

2021-02-18 08:48 UTC, urvashi-code1255 commented on assets/js/quiz.js
> +
remove extra space

2021-02-18 08:48 UTC, urvashi-code1255 commented on assets/js/quiz.js
> +
remove extra space

2021-02-18 14:20 UTC, closed without merging