Filterable Image Gallery
Vishal-raj-1/Awesome-JavaScript-Projects pull request #1555
Opened 2021-05-21 21:45 UTC by PritomDutta89

## Related Issue
 - Filterable Image Gallery

Closes: #1492 
### Describe the changes you've made
Added a project where you can filter images by your choice, made with HTML, CSS, JS.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots

![IMAGE FILTER 1](https://user-images.githubusercontent.com/76867403/119200775-3c5f8900-baab-11eb-8638-a2a07cda5f57.png)

![IMAGE FILTER 2](https://user-images.githubusercontent.com/76867403/119200799-45e8f100-baab-11eb-9489-e0ce663a5c9f.png)

![IMAGE FILTER 3](https://user-images.githubusercontent.com/76867403/119200807-48e3e180-baab-11eb-9b73-0df06ca8aa09.png)

![IMAGE FILTER 4](https://user-images.githubusercontent.com/76867403/119200812-4bded200-baab-11eb-9abf-14be9582ed20.png)

![IMAGE FILTER 5](https://user-images.githubusercontent.com/76867403/119200816-4f725900-baab-11eb-8b5a-91549a65387c.png)

![IMAGE FILTER 6](https://user-images.githubusercontent.com/76867403/119200818-51d4b300-baab-11eb-9a75-737a9202c2c5.png)

![IMAGE FILTER 7](https://user-images.githubusercontent.com/76867403/119200820-54370d00-baab-11eb-8c35-5c399ae411c2.png)

2021-05-21 21:56 UTC, PritomDutta89 commented
Please @ridsuteri @991rajat @urvashi-code1255 review this PR.

2021-05-22 17:05 UTC, ridsuteri requested changes
@PritomDutta89 the image of the project is not showing in the project card, please fix it, also resolve merge conflicts :)

2021-05-22 17:22 UTC, PritomDutta89 reviewed
now check

2021-05-22 18:18 UTC, ridsuteri requested changes
sorry @PritomDutta89 , the issue still persists :(

2021-05-22 18:51 UTC, PritomDutta89 commented
@ridsuteri what is project card?

2021-05-23 03:50 UTC, ridsuteri commented
> @ridsuteri what is project card?
this
![Screenshot (81)_LI](https://user-images.githubusercontent.com/59795822/119247552-15d34800-bba8-11eb-959a-0588d2a5f23e.jpg)

2021-05-23 05:00 UTC, PritomDutta89 commented
@ridsuteri Please can you help me how to fix it

2021-05-23 20:04 UTC, PritomDutta89 reviewed
by mistake

2021-05-23 20:20 UTC, PritomDutta89 commented
@ridsuteri Done, now check

2021-05-29 12:16 UTC, 991rajat commented on script.js
> +]
This is ending the list which is introducing error. Remove the square bracket.
But there are a lot of projects down below.

2021-05-29 12:16 UTC, 991rajat commented on script.js
>      projectUrl: "public/Restaurant.html"
Remove this line. It's duplicate.

2021-05-29 12:18 UTC, 991rajat reviewed
Look at the changes mentioned.

2021-05-29 12:41 UTC, PritomDutta89 commented on script.js
>      projectUrl: "public/Restaurant.html"
done

2021-05-29 12:45 UTC, PritomDutta89 commented
now check

2021-05-29 12:52 UTC, 991rajat commented
Remove these. They already exist.
![image](https://user-images.githubusercontent.com/38184186/120070991-c1016700-c0aa-11eb-8c2b-90115e21be45.png)

2021-05-29 12:57 UTC, PritomDutta89 commented
I don't understand, I have to these things here, I didn't add these things, I just added my file only

2021-05-29 13:03 UTC, 991rajat commented
Looks Good.

2021-05-29 13:03 UTC, 991rajat approved these changes
Good Work

2021-05-29 13:04 UTC, merged

2021-05-29 13:04 UTC, 991rajat commented
Congratulations on merging of first PR. :tada: 
Thanks for this awesome contribution.