Added Animated Unsubscribe Page
Vishal-raj-1/Awesome-JavaScript-Projects pull request #1566
Opened 2021-05-22 13:09 UTC by Shivangi-ch

## Related Issue
  - Added Animated Unsubscribe Page

Closes: #1500 

### Describe the changes you've made
Added Animated Unsubscribe Page

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
![unsub_page](https://user-images.githubusercontent.com/57783826/119227722-f8ad6380-bb2c-11eb-835e-af88d55ed051.png)

2021-05-22 13:09 UTC, Shivangi-ch commented
@ridsuteri @991rajat  Please review.

2021-05-22 18:15 UTC, ridsuteri requested changes
@Shivangi-ch the project doesn't work on my side :( , i.e nothing happens on clicking the buttons also please fix the image in the project card

2021-05-29 12:42 UTC, 991rajat commented on script.js
> +    projectImage: "assets/Images/unsub_page.png",
Link is not correct.
![image](https://user-images.githubusercontent.com/38184186/120070694-703d3e80-c0a9-11eb-8ee5-9e51f16ce456.png)

2021-05-29 12:43 UTC, 991rajat reviewed
Image is not loading. Fix that please.

2021-05-29 18:39 UTC, Shivangi-ch commented
@991rajat Issue Fixed.

2021-05-31 15:40 UTC, merged