added darkmode in signuplogin page
Vishal-raj-1/Awesome-JavaScript-Projects pull request #1856
Opened 2021-07-02 04:34 UTC by Srit20

Closes: #1841
### Describe the changes you've made
added darkmode in signuplogin page

### Screenshots
![Screenshot (368)](https://user-images.githubusercontent.com/80943355/124221182-dbe95000-db1c-11eb-8050-7d424b91c488.png)
![Screenshot (367)](https://user-images.githubusercontent.com/80943355/124221187-ddb31380-db1c-11eb-8ee3-5a6603c421ec.png)

2021-07-02 11:47 UTC, Rizwan-S requested changes

2021-07-02 11:47 UTC, Rizwan-S commented on signuplogin.html
> +	</nav>
Something is wrong with the code of toggle button. The changes are not reflected and hence the button is not visible.

2021-07-07 15:26 UTC, Vishal-raj-1 commented
@Srit20 Any update from your side ?

2021-07-08 06:05 UTC, Srit20 commented
sir i have already done it 4 days ago #1841

On Wed, Jul 7, 2021 at 8:56 PM Vishal Rajput ***@***.***>
wrote:

> @Srit20 <https://github.com/Srit20> Any update from your side ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/pull/1856#issuecomment-875700459>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATJRR64JGT7TBW2UNGL55LLTWRW3DANCNFSM47V6QUYA>
> .
>

2021-07-08 06:07 UTC, Srit20 commented
sir i have already done it 4 days ago and it is closed by #1871

On Thu, Jul 8, 2021 at 11:35 AM 19cse098 sritamsubudhi <
***@***.***> wrote:

> sir i have already done it 4 days ago #1841
>
> On Wed, Jul 7, 2021 at 8:56 PM Vishal Rajput ***@***.***>
> wrote:
>
>> @Srit20 <https://github.com/Srit20> Any update from your side ?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/pull/1856#issuecomment-875700459>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ATJRR64JGT7TBW2UNGL55LLTWRW3DANCNFSM47V6QUYA>
>> .
>>
>

2021-07-08 10:03 UTC, closed without merging