Random Password Generator Added
Vishal-raj-1/Awesome-JavaScript-Projects pull request #1896
Opened 2021-07-15 18:34 UTC by joshi-kaushal

## Related Issue
  -Created a password generator that generates a random password containing when length and criteria is selected.  

### Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
![image](https://user-images.githubusercontent.com/53049546/125839614-922f6aa3-9746-47e8-b408-5d70e858faff.png)

2021-07-16 16:22 UTC, Rizwan-S requested changes
Please remove 'linechart.html'. If you wish to add linechat, please make a separate pr. Multiple issues solved in a single pr will cause problem in allocating points. As a result, you'll get points only for a single issue.  Also, it is a bad practice in open source to make a pr for an issue assigned to others. Please take care of this from next time :)

2021-07-16 18:20 UTC, joshi-kaushal commented
Extremely sorry, I'll make the changes ASAP

2021-07-16 18:48 UTC, joshi-kaushal commented
@Rizwan-S please have a look

2021-07-17 03:10 UTC, Rizwan-S commented
I think you have removed the wrong file

2021-07-17 05:12 UTC, joshi-kaushal reviewed
I have deleted a `linechart.html` file so please have a look

2021-07-17 11:32 UTC, Rizwan-S requested changes

2021-07-17 11:32 UTC, Rizwan-S commented on script.js
> -  },
Please don't remove this code.

2021-07-18 16:15 UTC, joshi-kaushal commented
@Rizwan-S please have a look, `git pull` might have caused addition of some updated information

2021-07-18 16:21 UTC, Rizwan-S approved these changes
Excellent!!!

2021-07-18 16:22 UTC, merged