Radar Chart added
Vishal-raj-1/Awesome-JavaScript-Projects pull request #1898
Opened 2021-07-16 14:33 UTC by joshi-kaushal

## Related Issue
  - Added a project that creates a Radar Chart based on the user inputs

### Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
![image](https://user-images.githubusercontent.com/53049546/125964151-bd9f7eb1-3b49-4e73-9865-9dd7e1649216.png)

2021-07-16 16:27 UTC, Rizwan-S requested changes
Please remove 'linechart.html' file

2021-07-16 18:18 UTC, joshi-kaushal commented
@Rizwan-S along with its image and mention in script.js or just html file?

2021-07-16 18:38 UTC, joshi-kaushal commented
@Rizwan-S please have a look.

2021-07-17 11:35 UTC, Rizwan-S requested changes
Please remove the 'password.html', 'password-generator.jpg' files

2021-07-17 11:37 UTC, Rizwan-S commented on script.js
> -    projectUrl: "public/barchart.html",
Bar Chart project is already present. Please don't remove this code.

2021-07-18 16:08 UTC, joshi-kaushal commented
@Rizwan-S please check, i did `git pull` once so has some updated info.

2021-07-18 16:35 UTC, Rizwan-S requested changes
Please move the radar.html file to public folder.

2021-07-19 05:46 UTC, Rizwan-S approved these changes
Excellent!!!

2021-07-19 05:47 UTC, merged