Adding the Sudoku Project
Vishal-raj-1/Awesome-JavaScript-Projects pull request #1900
Opened 2021-07-17 20:50 UTC by soma2000-lang

## Related Issue
  - The project is done using html ,javascript and css using the concept of backtracking

#1899

### Describe the changes you've made
Added all the files of the Sudoku Solver

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.

### Screenshots
![WhatsApp Image 2021-07-18 at 02 19 06 (1)](https://user-images.githubusercontent.com/56045049/126049067-c9c5f45e-f01f-4f2d-b5d0-c1c9964f9a0b.jpeg)

2021-07-17 20:51 UTC, soma2000-lang commented
@Rizwan-S 
Please look into this pull request

2021-07-18 03:51 UTC, Rizwan-S requested changes
Please follow the folder structure of the project. Put the html file in public folder and js, css files in relevant folders of assets folder. Also, please remove README file and also update this project's script.js file.

2021-07-18 04:16 UTC, soma2000-lang commented
@Rizwan-S 
What changes shoud be done in script.js files

2021-07-18 04:26 UTC, Rizwan-S commented
You need to add your project in the array.

2021-07-18 12:42 UTC, soma2000-lang commented
@Rizwan-S  made all thr changes ,Please look into it

2021-07-18 13:55 UTC, Rizwan-S requested changes
Please rename 'Sudoku Solver.html' to 'Sudoku_Solver.html' & 'Sudoku Solver.jpeg' to 'Sudoku_Solver.jpeg'

2021-07-18 14:29 UTC, soma2000-lang commented
@Rizwan-S  done

2021-07-18 16:26 UTC, Rizwan-S commented
You need to rename the js and css file also. My bad, I didn't notice it first :(

2021-07-18 16:49 UTC, Rizwan-S requested changes

2021-07-18 16:49 UTC, Rizwan-S commented on public/Sudoku_Solver.html
> +    <script defer src="script.js"></script>
Use '../assets/js/Sudoku_Solver.js' as script src.

2021-07-18 16:49 UTC, Rizwan-S commented on public/Sudoku_Solver.html
> +    <link rel="stylesheet" href="style.css">
Use '../assets/css/Sudoku_Solver.css' as href

2021-07-18 18:59 UTC, soma2000-lang commented
@Rizwan-S  Sir made the modifications.

2021-07-19 03:39 UTC, Rizwan-S commented
Dude, this is wrong. Not everyone will place your files at that specific location. Please use what I mentioned.

2021-07-19 08:14 UTC, soma2000-lang commented
@Rizwan-S  Sorry for my  mistake
Check now

2021-07-19 13:40 UTC, Rizwan-S approved these changes
Great Work!!!

2021-07-19 13:42 UTC, merged

2021-07-19 13:45 UTC, soma2000-lang commented
Thank you sir

On Mon, Jul 19, 2021, 19:12 github-actions[bot] ***@***.***>
wrote:

> Thank you @soma2000-lang <https://github.com/soma2000-lang> for taking
> out your valuable time in order to contribute to our project. Looking
> forward for more such amazing contributions :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/pull/1900#issuecomment-882558724>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANLS36N5JF6HXRKHJ5BL4JLTYQTVDANCNFSM5ARNC36Q>
> .
>