Drawing App
Vishal-raj-1/Awesome-JavaScript-Projects pull request #1910
Opened 2021-07-25 20:12 UTC by Sulagna-Dutta-Roy

## Related Issue
  - Info about Issue or bug
  I've added the drawing app as an additional project using Javascript.

Closes: #[issue number that will be closed through this PR]
#1908 

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
I've added all the files in this project.The project is drawing app using Javascript. There is an small canvas that let user can do anything they want. The user can draw and erase their painting.Reset option also provided.The slider can increase or decrease the paint color fill.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.
NA
### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
![Drawing](https://user-images.githubusercontent.com/72568715/126912054-32d45c75-a7d9-4770-828a-a8683601146c.PNG)
![Drawing1](https://user-images.githubusercontent.com/72568715/126912057-359b6dbb-8fe0-476a-90d0-19310811b0aa.PNG)

2021-07-27 13:31 UTC, Rizwan-S requested changes
Hello! I think you forgot to add the project details in script.js file. The changes won't be reflected until you add your project details there.

2021-07-29 08:31 UTC, Rizwan-S requested changes
Hello! I think you have misunderstood the request. You need to add the project details to script.js file. 
Here is the link to the file which I am talking about: [https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/blob/main/script.js](https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects/blob/main/script.js) .
Also, the css and js files needs to be in assets folder in their respective directories.

2021-07-30 03:58 UTC, Rizwan-S requested changes
Everything is good. However, you still need to move the js and css files in assets folder.

2021-07-31 08:49 UTC, Sulagna-Dutta-Roy commented
I've done the changes. Please check sir

2021-07-31 16:39 UTC, Rizwan-S requested changes

2021-07-31 16:39 UTC, Rizwan-S commented on public/Drawing App/index.html
> +        <link rel="stylesheet" href="style.css">
should  be 
```
<link rel="stylesheet" href="../../assets/css/Drawing App/style.css">
```

2021-07-31 16:39 UTC, Rizwan-S commented on public/Drawing App/index.html
> +        <script src="script.js"></script>
Should be
```
<script src="../../assets/js/Drawing App/script.js"></script>
```

2021-07-31 17:56 UTC, Sulagna-Dutta-Roy commented
Done

2021-08-09 08:40 UTC, Rizwan-S approved these changes

2021-08-09 08:56 UTC, Vishal-raj-1 approved these changes

2021-08-09 09:04 UTC, merged