Insect Catch Game
Vishal-raj-1/Awesome-JavaScript-Projects pull request #226
Opened 2021-03-05 21:34 UTC by Ayush7614

## Related Issue
  - #166 

Closes: #[166]

### Describe the changes you've made
Added a game of insect catching game in html css js

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

### Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

2021-03-05 21:35 UTC, Ayush7614 commented
Plss review it @Vishal-raj-1 and this pull is for issue no #166

2021-03-06 12:39 UTC, urvashi-code1255 reviewed
@Ayush7614 Correct the paths everywhere!

Also change the card image with GIF

2021-03-06 19:37 UTC, Ayush7614 commented
@urvashi-code1255 now you can review it

2021-03-08 04:25 UTC, urvashi-code1255 commented
@Ayush7614 Resolve the merge conflicts!

Write "closes: #166" in the PR description.

2021-03-10 15:07 UTC, urvashi-code1255 commented on script.js
> +=======
@Ayush7614 remove this

2021-03-20 05:43 UTC, Ayush7614 commented
@urvashi-code1255 now you can see it its correct or not

2021-03-20 12:04 UTC, urvashi-code1255 commented
@Ayush7614 Its not Okay Yet. Check the website locally.

2021-04-03 16:44 UTC, urvashi-code1255 requested changes

2021-04-03 16:44 UTC, urvashi-code1255 commented on script.js
> +    projectName: "Animated Minion Eyes",
put the open curly brace here

2021-04-03 16:44 UTC, urvashi-code1255 commented on script.js
>      projectName: 'Exchange Rate',
put the open curly brace here

2021-04-12 08:37 UTC, Vishal-raj-1 commented
@Ayush7614 ??

2021-04-15 04:00 UTC, Ayush7614 commented
@urvashi-code1255 @Vishal-raj-1 now you can review it its correct or not

2021-04-19 09:58 UTC, harshgupta20 commented
@Ayush7614 Kindly commit on separate branch, pls don't commit on master or main branch.

2021-05-29 17:27 UTC, merged