Guruc-134 markdown previewer
Vishal-raj-1/Awesome-JavaScript-Projects pull request #470
Opened 2021-03-15 09:00 UTC by guruc-134

## Related Issue
  New Project: Markdown Previewer
  
Closes: #[issue number that will be closed through this PR]
issue: #299 
### Describe the changes you've made
This is a markdown previewer, Here the user enters his text in the markdown format, and it gets rendered dynamically and  displayed on the previewer

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
`NA`

### Checklist:

- [ x ] My code follows the style guidelines of this project.
- [ x ] I have performed a self-review of my own code.
- [ x ] I have commented my code, particularly in hard-to-understand areas.
- [ x ] I have made corresponding changes to the documentation.
- [ x ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

![image](https://user-images.githubusercontent.com/70446767/111128404-d92d1400-859a-11eb-9467-fa11e75657db.png)

2021-03-16 20:51 UTC, urvashi-code1255 commented
@guruc-134 Resolve the mergee conflicts

2021-03-17 13:42 UTC, guruc-134 commented
@urvashi-code1255  removed the duplicate file names present in the scripts.js

2021-03-18 06:55 UTC, ridsuteri commented on .vscode/settings.json
> +{
any use of this file?

2021-03-18 06:58 UTC, ridsuteri requested changes
@guruc-134 add this project to the script.js file

2021-03-18 17:33 UTC, closed without merging