Added custom video player
Vishal-raj-1/Awesome-JavaScript-Projects pull request #525
Opened 2021-03-17 13:24 UTC by FireQueen-3010

## Related Issue
Made a Custom Video player using Javascript

Closes: #[#463]

### Describe the changes you've made
I added the necessary javascript, html and css files corresponding to the project and tested them.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.
![image](https://user-images.githubusercontent.com/59244300/111474469-1ee00d00-8752-11eb-932f-506519f1261f.png)

2021-03-17 13:25 UTC, FireQueen-3010 commented
Please review my pr @ridsuteri

2021-03-18 05:51 UTC, ridsuteri requested changes
@FireQueen-3010 kindly add detials of this project in the script.js file

2021-03-18 05:52 UTC, FireQueen-3010 commented
Ok

2021-03-18 06:16 UTC, FireQueen-3010 commented
Made the changes please review @ridsuteri

2021-03-18 06:42 UTC, ridsuteri requested changes
your PR contains some commits which are breaking Expanding card project
kindly fix that

2021-03-18 06:43 UTC, ridsuteri commented on public/ExpandingCard.html
> +    <link rel = "stylesheet" href="../assets/css/Expanding card.css">
Css file not linked properly 
make it ExpandingCard.css

2021-03-18 06:43 UTC, ridsuteri commented on public/ExpandingCard.html
> +    <script src="../assets/js/Expanding card.js"></script>
js file not linked properly
make it ExpandingCard.js

2021-03-18 06:44 UTC, ridsuteri requested changes
these are the changes required

2021-03-18 08:30 UTC, FireQueen-3010 commented
ok

2021-03-18 12:28 UTC, FireQueen-3010 commented
Done @ridsuteri

2021-03-18 13:45 UTC, ridsuteri approved these changes
great work @FireQueen-3010 ,thanks for contributing :)

2021-03-18 13:45 UTC, merged

2021-03-18 14:37 UTC, FireQueen-3010 commented
Thank you @ridsuteri . Please add gssoc and level tags else I cannot receive my pts :)