Added files and updated script.js
Vishal-raj-1/Awesome-JavaScript-Projects pull request #596
Opened 2021-03-21 17:36 UTC by sejalxz

## Related Issue
  - Added TV Show Search Project

Closes: #501 

### Describe the changes you've made
* I added the necessary JavaScript, HTML and CSS files for my TV Show Search project.
* Updated script.js

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
![Tv_Show_Search](https://user-images.githubusercontent.com/71432400/111914912-fdf12200-8a99-11eb-9629-500b28f56766.png)

2021-03-28 17:16 UTC, sejalxz commented
@991rajat @urvashi-code1255 I have resolved the conflicts. Please look into it. Thanks :)

2021-03-30 06:04 UTC, 991rajat commented on script.js
> +    projectUrl: "public/TV_Show_Search.html",
Not Properly Linked. Typo Error

2021-03-30 06:07 UTC, 991rajat requested changes
Good Work
One Suggestion Could you it centered in mobile View
<img src="https://user-images.githubusercontent.com/38184186/112941376-1d4c1700-914c-11eb-941d-87333c32c0f5.png" height=200/>

2021-04-07 17:09 UTC, 991rajat commented
@sejalxz Similar PR is opened by you. I'm closing this.

2021-04-07 17:09 UTC, closed without merging