Added MemeUrl
Vishal-raj-1/Awesome-JavaScript-Projects pull request #687
Opened 2021-03-28 04:58 UTC by mohammedjameel24

## Added MEME Url project

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
![image](https://user-images.githubusercontent.com/80387413/112742522-e12e8000-8fac-11eb-8461-987fc4a26a7c.png)

2021-03-28 05:03 UTC, mohammedjameel24 commented
merge my pull request @ridsuteri

2021-03-28 05:29 UTC, mohammedjameel24 commented
merge

2021-03-29 17:00 UTC, ridsuteri requested changes
@mohammedjameel24 this project is not working on my side...
please check once again and do the changes ,if required

2021-03-29 17:24 UTC, mohammedjameel24 commented
> @mohammedjameel24 this project is not working on my side...
> please check once again and do the changes ,if required

Is it not even displaying of not creating posts?

2021-03-29 17:33 UTC, mohammedjameel24 commented
commited into different pull #700

2021-03-30 01:51 UTC, ridsuteri commented on script.js
>      projectName: 'Animated Minion Eyes',
{ is misssing after line 221

2021-03-30 01:53 UTC, ridsuteri requested changes
@mohammedjameel24 there is some issue with script file ,please resolve it and check locally before putting a PR ,rest your project is working fine :)

2021-03-30 09:13 UTC, mohammedjameel24 commented
now?

2021-04-01 11:52 UTC, mohammedjameel24 commented
Please merge my pull request

2021-04-01 11:52 UTC, mohammedjameel24 commented
Please merge my pull request@ridsuteri

2021-04-04 16:34 UTC, ridsuteri requested changes
nopes @mohammedjameel24 still not working properly...
Your script file is creating problems...
Please check locally on your system before opening a PR

2021-04-04 16:56 UTC, mohammedjameel24 commented
Memeurl.js ? Or script.js?

2021-04-04 16:58 UTC, ridsuteri commented
@mohammedjameel24 script.js

2021-04-04 17:04 UTC, mohammedjameel24 commented
please tell me now?

2021-04-04 17:17 UTC, ridsuteri approved these changes
done @mohammedjameel24 ,thanks for contributing :)

2021-04-04 17:17 UTC, merged