added music player game
Vishal-raj-1/Awesome-JavaScript-Projects pull request #75
Opened 2021-02-14 14:45 UTC by Sloth-Panda

Corresponds to issue-> #56 

@urvashi-code1255 now its fine 
![Screenshot (121)](https://user-images.githubusercontent.com/70213384/107879845-4ba9c600-6f01-11eb-874a-3c5f0e6b8dc5.png)

2021-02-14 19:26 UTC, Vishal-raj-1 requested changes
@Sloth-Panda Good work !! Projects seems awesome to me, just focus on code formatting as well.

2021-02-14 19:26 UTC, Vishal-raj-1 commented on assets/css/musicplayer.css
> +
There should be only one line gap. Remove extra line !!

2021-02-14 19:26 UTC, Vishal-raj-1 commented on assets/css/musicplayer.css
> +
There should not be any line gap !!

2021-02-14 19:26 UTC, Vishal-raj-1 commented on assets/css/musicplayer.css
> +
There should not be any line gap in all .pad-{1,2,3,4,5}!!

2021-02-15 04:37 UTC, Sloth-Panda commented
@Vishal-raj-1 @urvashi-code1255  is it okay now?

I actually resolved the conflicts here on github and made that commit but that was just the conflict in index page which I resolved.
After that I took a pull of code from upstream/main and their made the required changes that you mentioned  but when I am trying to push the code to it shows like this even I tried pull then push still shows like this to me
![Screenshot (123)](https://user-images.githubusercontent.com/70213384/107905729-63229680-6f75-11eb-93e5-fa1e59ca346c.png)

so what to do ?

2021-02-15 10:09 UTC, Vishal-raj-1 commented
did you commit your changes  ? first commit your changes then do `git pull upstream master` not `git pull` then push.

2021-02-15 12:32 UTC, Sloth-Panda commented
@Vishal-raj-1 I am still not able to push, I have updated my repo with the upstream but still not able to push why's that??

![Screenshot (127)](https://user-images.githubusercontent.com/70213384/107947023-d3520c00-6fb7-11eb-8ff0-eb04b0bbcd45.png)

2021-02-15 12:49 UTC, Sloth-Panda commented
@Vishal-raj-1 bro, I checked out a new branch and pushed the code to that branch and the push worked also every other thing works fine so for these issues can I make a single separate pr? and close these two separate prs?

2021-02-15 17:19 UTC, Sloth-Panda commented
@urvashi-code1255, I have some doubts (1). I see when I am making one pr, it is having commits of the previous prs I mean how can  I make commits for only one issue in one pr? Like here you saw what should have been 3 prs commits got merged in 1pr?
(2) how can I get this site or sites like this to work https://Sloth-Panda.github.io/

2021-02-15 17:32 UTC, urvashi-code1255 commented
> @urvashi-code1255, I have some doubts (1). I see when I am making one pr, it is having commits of the previous prs I mean how can I make commits for only one issue in one pr? Like here you saw what should have been 3 prs commits got merged in 1pr?

@Sloth-Panda To make PRs with different changes, you should make all the PRs from seperate branches
> (2) how can I get this site or sites like this to work https://Sloth-Panda.github.io/

I didn't get your point!!

2021-02-15 18:06 UTC, closed without merging