Amit
Vishal-raj-1/Awesome-JavaScript-Projects pull request #880
Opened 2021-04-07 15:55 UTC by Amit366

## Related Issue
  Added Speech to text converter

Closes: #872 

### Describe the changes you've made
Added a code that converts speech to text.

### Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
![Screenshot (180)](https://user-images.githubusercontent.com/60662775/113896661-c697aa80-97e7-11eb-9d9a-78967daa18fa.png)

2021-04-08 10:21 UTC, Amit366 commented
@ridsuteri please review it.

2021-04-08 14:23 UTC, ridsuteri requested changes
there is a little fix needed at line 562 in script.js ,please resolve it

2021-04-08 14:23 UTC, ridsuteri commented on script.js
> +  }
, is missing after line 562
please add it

2021-04-08 15:20 UTC, Amit366 commented
@ridsuteri now is it fine??

2021-04-09 14:45 UTC, Amit366 commented
@ridsuteri please review it. It is getting merge conflicts.

2021-04-09 16:07 UTC, ridsuteri approved these changes
good work @Amit366 thanks for contributing :)

2021-04-09 16:07 UTC, merged