Pricing cards
Vishal-raj-1/Awesome-JavaScript-Projects pull request #987
Opened 2021-04-13 14:10 UTC by vinc3nati

## Related Issue
  - This issue solves the aged way of displaying pricing plan cards by adding user experience and interactivity.

Closes: #914  

### Describe the changes you've made
- I have added  "PricingCards.html" --> public  
- "pricingCards.css" --> css 
- "PricingCards" folder --> Images 
- Updated "script.js"

### Describe if there is any unusual behaviour of your code(Write NA if there isn't)
NA

### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
**Front Side**
> ![image](https://user-images.githubusercontent.com/48097586/114566059-8628a880-9c8f-11eb-82bb-43aefb0c73ab.png)

**Popup**
> ![image](https://user-images.githubusercontent.com/48097586/114566390-d7d13300-9c8f-11eb-814a-074367cacab1.png)

2021-04-13 15:24 UTC, urvashi-code1255 reviewed
@vinc3nati You haven't added your project's GIF in assets folder.

2021-04-14 05:03 UTC, vinc3nati commented
> @vinc3nati You haven't added your project's GIF in assets folder.

Yes I have updated it's in the folder <PricingCards> in the GIFs section.

2021-04-14 12:51 UTC, vinc3nati commented
> @vinc3nati You haven't added your project's GIF in assets folder.

Hello there , I have updated the GIFs folder with the project's gif file. Hope everything is fine now.

2021-04-14 16:44 UTC, urvashi-code1255 commented
@vinc3nati Haven't you used any Js in your project?

2021-04-14 17:06 UTC, vinc3nati commented
> @vinc3nati Haven't you used any Js in your project?

Yes I had planned on using it but sass made things easy for me.
Nonetheless if you want me to add js Lemme know I'll do the same.

2021-04-14 17:18 UTC, urvashi-code1255 commented
@vinc3nati As this website is for vanilla js projects. I request you to do this with vanilla js.

2021-04-15 03:55 UTC, vinc3nati commented
> @vinc3nati As this website is for vanilla js projects. I request you to do this with vanilla js.

Roger that.

2021-04-15 13:06 UTC, vinc3nati commented
Hey @urvashi-code1255 Vanilla JS has been added as you asked for.

2021-04-17 05:04 UTC, vinc3nati commented
Hey @urvashi-code1255 is there any problem with my pull request because it's been pending since 2 days?

2021-04-20 12:31 UTC, 991rajat commented on script.js
> +=======
Remove this merge conflict tags.

2021-04-20 12:32 UTC, 991rajat requested changes
Reduce the size of the gif please.
If not able to reduce replace with the static image.

2021-04-20 12:47 UTC, vinc3nati commented on script.js
> +=======
Roger that

2021-04-20 12:47 UTC, vinc3nati commented
> Reduce the size of the gif please.
> If not able to reduce replace with the static image.

On it

2021-04-20 13:23 UTC, vinc3nati commented
Reduced the size of  the gif and fixed the merge conflict. @urvashi-code1255 @991rajat

2021-04-20 13:55 UTC, 991rajat approved these changes
Looks Great.

2021-04-20 13:56 UTC, merged

2021-04-20 13:57 UTC, 991rajat commented
Thanks for this awesome contribution. 🤩 
Keep Contributing.

2021-04-20 13:57 UTC, 991rajat commented
Learn about squashing the commits. It's a good practice.

2021-04-20 14:13 UTC, vinc3nati commented
Gotcha.